
TARGET_NO_BOOTLOADER := true
TAREGT_NO_RECOVERY := true

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a72

# Secondary Arch
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a72

TARGET_USES_64_BIT_BINDER := true

#Treble
PRODUCT_FULL_TREBLE_OVERRIDE := true
BOARD_VNDK_VERSION := current

# Use mke2fs to create ext4 images
TARGET_USES_HWC2 := true

DEVICE_MANIFEST_FILE := device/brcm/rpi4/manifest.xml
DEVICE_MATRIX_FILE := device/brcm/rpi4/compatibility_matrix.xml

PRODUCT_ENFORCE_VINTF_MANIFEST_OVERRIDE := true

BOARD_FLASH_BLOCK_SIZE := 4096

BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2097152000 # 2GB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 134217728 # 128M
BOARD_VENDORIMAGE_PARTITION_SIZE := 268435456 # 256M

TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

# THIS IS JUST FAKE!!!
# we still only need kernel but with this we can build all with a single make call
#BOARD_BOOTIMAGE_PARTITION_SIZE := 43948032
#BOARD_RECOVERYIMAGE_PARTITION_SIZE := 43948032

#BOARD_ROOT_EXTRA_FOLDERS := boot

TARGET_BOARD_PLATFORM := bcm2711
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := system/product
TARGET_COPY_OUT_SYSTEM_EXT := system/system_ext

#BOARD_SEPOLICY_DIRS := \
#    $(DEVICE_PATH)/sepolicy

MALLOC_SVELTE := true
USE_XML_AUDIO_POLICY_CONF := 1

BOARD_KERNEL_IMAGE_NAME := Image
TARGET_KERNEL_CONFIG := lineageos_rpi4_defconfig
TARGET_KERNEL_CLANG_COMPILE := false

BOARD_MESA3D_USES_MESON_BUILD := true
BOARD_MESA3D_GALLIUM_DRIVERS := v3d vc4
BOARD_MESA3D_VULKAN_DRIVERS := broadcom
USE_OPENGL_RENDERER := true

# Wifi
BOARD_WLAN_DEVICE := bcmdhd
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_bcmdhd
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB   := lib_driver_cmd_bcmdhd

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/brcm/rpi4/bluetooth
BOARD_CUSTOM_BT_CONFIG := device/brcm/rpi4/bluetooth/vnd_rpi4.txt

#Camera
BOARD_LIBCAMERA_USES_MESON_BUILD := true
BOARD_LIBCAMERA_IPAS := raspberrypi
BOARD_LIBCAMERA_PIPELINES := raspberrypi

BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

TARGET_SYSTEM_PROP := device/brcm/rpi4/vendor.prop

ifeq ($(TARGET_NO_RECOVERY),true)
#BOARD_USES_RECOVERY_AS_BOOT := true
endif

ifeq ($(TARGET_NO_RECOVERY),false)
#TARGET_RECOVERY_FSTAB := device/brcm/rpi4/recovery/root/system/etc/recovery.fstab
#TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
#TARGET_RECOVERY_FORCE_PIXEL_FORMAT := "RGB_565"
endif