#!/vendor/bin/sh

#
# Copyright (C) 2019-2023 KonstaKANG <konstakang@gmail.com>
#
# SPDX-License-Identifier: CC-BY-NC-SA-4.0
#

ECDSA_KEY=/data/ssh/ssh_host_ecdsa_key
ECDSA_PUB_KEY=/data/ssh/ssh_host_ecdsa_key.pub
ED25519_KEY=/data/ssh/ssh_host_ed25519_key
ED25519_PUB_KEY=/data/ssh/ssh_host_ed25519_key.pub
RSA_KEY=/data/ssh/ssh_host_rsa_key
RSA_PUB_KEY=/data/ssh/ssh_host_rsa_key.pub
AUTHORIZED_KEYS=/data/ssh/authorized_keys
SSHD_CONFIG=/data/ssh/sshd_config

if [ ! -f $ECDSA_KEY ]; then
  /system/bin/ssh-keygen -t ecdsa -f $ECDSA_KEY -N ""
  chmod 600 $ECDSA_KEY
  chmod 644 $ECDSA_PUB_KEY
fi

if [ ! -f $ED25519_KEY ]; then
  /system/bin/ssh-keygen -t ed25519 -f $ED25519_KEY -N ""
  chmod 600 $ED25519_KEY
  chmod 644 $ED25519_PUB_KEY
fi

if [ ! -f $RSA_KEY ]; then
  /system/bin/ssh-keygen -t rsa -f $RSA_KEY -N ""
  chmod 600 $RSA_KEY
  chmod 644 $RSA_PUB_KEY
fi

if [ ! -f $AUTHORIZED_KEYS ]; then
  cat $ECDSA_PUB_KEY > $AUTHORIZED_KEYS
  cat $ED25519_PUB_KEY >> $AUTHORIZED_KEYS
  cat $RSA_PUB_KEY >> $AUTHORIZED_KEYS
fi

if [ ! -f $SSHD_CONFIG ]; then
  cp /system/etc/ssh/sshd_config $SSHD_CONFIG
fi
